FROM node:20-alpine

ARG DATABASE_URL
RUN echo "$DATABASE_URL"
ARG PONDER_ETH_INFURA
RUN echo "$PONDER_ETH_INFURA"
ARG PONDER_OPT_INFURA
RUN echo "$PONDER_OPT_INFURA"
ARG PONDER_RPC_URL_1
RUN echo "$PONDER_RPC_URL_1"
ARG PONDER_RPC_URL_10
RUN echo "$PONDER_RPC_URL_10"
ARG PONDER_RPC_URL_10_FALLBACK
RUN echo "$PONDER_RPC_URL_10_FALLBACK"
ARG PONDER_RPC_URL_1_FALLBACK
RUN echo "$PONDER_RPC_URL_1_FALLBACK"
ARG PONDER_RPC_URL_7777777
RUN echo "$PONDER_RPC_URL_7777777"
ARG PONDER_RPC_URL_8453
RUN echo "$PONDER_RPC_URL_8453"
ARG PONDER_RPC_URL_8453_FALLBACK
RUN echo "$PONDER_RPC_URL_8453_FALLBACK"

WORKDIR /usr/src/app

COPY package.json ./
COPY yarn.lock ./
RUN yarn install

COPY . .

EXPOSE 42069

CMD ["yarn" ,"start"]